name: Ruby Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: '2.7.7'
            gemfile: 'rails5'
          - ruby-version: '3.0.5'
            gemfile: 'rails6'
          - ruby-version: '3.0.5'
            gemfile: 'rails7'
          - ruby-version: '3.1.3'
            gemfile: 'rails6'
          - ruby-version: '3.1.3'
            gemfile: 'rails7'
          - ruby-version: '3.2.0'
            gemfile: 'rails7'

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@cd9d3de43b264c20364fa16fc29fb0e0f3ebbd12
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake