name: Ruby Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # ruby-version: [ '2.6.7', '3.0.1', '3.0.2', '3.1.1' ]
        ruby-version: [ '3.0.1', '3.0.2', '3.1.1' ]
        gemfile: [ 'rails5','rails6', 'rails7' ]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@cd9d3de43b264c20364fa16fc29fb0e0f3ebbd12
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake